<?php
/**
 * @file
 * Drupal module for displaying full-text version of Ting objects.
 *
 * This uses a docbook-subset for displaying content.
 */

/**
 * Implements hook_theme().
 */
function ting_fulltext_theme($existing, $type, $theme, $path) {
  return array(
    'ting_fulltext' => array(
      'arguments' => array('element' => NULL),
      'template' => 'ting_fulltext_view',
    ),
  );
}

/**
 * Loader function to get the fulltext object as raw data(xml) for parsing.
 */
function ting_fulltext_object_load($object_id) {
  if (empty($object_id)) {
    return FALSE;
  }

  module_load_include('client.inc', 'ting');
  $xml = '';

  if (empty($xml)) {
    // Configure basic object search.
    $request = ting_get_request_factory()->getObjectRequest();
    $request->setObjectId($object_id);

    // Add agency and profile.
    $request = ting_add_agency($request);
    $request = ting_add_profile($request);

    // We want docbook back as XML.
    $request->setObjectFormat('docbook');
    $request->setOutputType('xml');
    $xml = ting_execute($request);
  }

  return $xml;
}
